@startuml
title Blend flow

User --> AllTrack: Click on line item

AllTrack -> OrdersAPI: Get blend data 
note over AllTrack: /sellproducts/orders/{id}/lines/{line-id}/workorder
OrdersAPI -> BlendAPI: Get blend data
note over BlendAPI: no blend found
BlendAPI -> OrdersAPI: No records found
OrdersAPI -> AllTrack: No records found
@enduml