name: Generate PlantUML Diagrams
on:
  push:
    paths:
      # any time a puml file is updated, or the github action file is updated
      - '**.puml'
      - '**/plantuml.yml'
    branches:
      - master
jobs:
  generate-architecture-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate architecture docs
        run: java -jar ./docs/plantuml.jar -v -tpng -tsvg ./docs
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_message: "Generate images for PlantUML diagrams" 
