name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'
      - '**\*.plantuml.yml'
    branches:
      - master
jobs:
  generate-architecture-images:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg '.\docs\'
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng '.\docs\'
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "PlantUML Generator"
          commit_user_email: "nobody@gmail.com"
          commit_author: "PlantUML Generator <nobody@gmail.com>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
